<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net9.0</TargetFrameworks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Version>4.0.0</Version>
    <PackageTags>
      bus;esb;service;soa;publish;subscribe;messaging;event;architecture;pub;sub;queue;servicebus</PackageTags>
    <Description>EzBus - Messaging made easy!</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\EzBus\EzBus.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.3" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.3" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.3" />
  </ItemGroup>
</Project>